### ISSUE TITLE
Unable to remove station

### ISSUE THREAD

**Issue by paulwakeford** [ianByrne/HASS-ukho_tides#26]
Hi, have been running UKHO for ages now and it’s worked really well - thanks. 

A few months ago however my card stopped working. My card is for a station for Exmouth Approaches which it looks like has been renamed or changed to Exmouth Dock. This means when I use the config flow I have a station called ‘0026B’ in the Stations list that I’m not able to remove as it’s not in the dropdown list and if I try to add Exmouth Dock then the config won’t save as there is an invalid station. 

I’ve also not been able to find where the config is stored to manually remove this entry. Any ideas please? Thanks.

**Comment by ianByrne** [comment]
Hi @paulwakeford, I'm sorry to hear that you're running into some issues with the stations. It does indeed sound like the name change may have muddled things up in the background.

I'm afraid that when you use the config flow through the UI, it's not easy to manually modify the underlying data. I would suggest completely removing the integration (and ensuring that all the entities have been removed as well, and manually removing any that lingered), and then re-adding the integration. You can then either try the config flow again for Exmouth Dock, or failing that, try adding it as a configuration.yaml entry (I note its station Id is apparently `0027`).

You will also probably need to update the entity Id to be the same as your old one so that your existing automations and cards work again.

Please let me know how you go

**Comment by paulwakeford** [comment]
Confirmed that remove and re-add worked - thanks.

**Comment by paulwakeford** [comment]
Issue resolved.
